### ISSUE TITLE
Cannot Nix build on Mac M1

### ISSUE THREAD

**Issue by ostrolucky** [peterldowns/nix-search-cli#7] opened 2023-03-24 08:41 UTC
```
❯ nix run github:peterldowns/nix-search-cli -- --help
error: builder for '/nix/store/d3b79195anc6303dpdjr480qv0bnslfk-ansi-escapes_v0.2.0.drv' failed with exit code 1;
       last 1 log lines:
       > go: github.com/snugfox/ansi-escapes@v0.2.0: Get "https://proxy.golang.org/github.com/snugfox/ansi-escapes/@v/v0.2.0.info": x509: OSStatus -26276
       For full logs, run 'nix log /nix/store/d3b79195anc6303dpdjr480qv0bnslfk-ansi-escapes_v0.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/dwin1bmf0vk3w3km072vnfc493a99n29-vendor-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/r0403ygrjxblbhzv899jbcr60s7zx49h-nix-search-cli-0.0.3.drv' failed to build
```

**Comment by peterldowns** [comment] 2023-03-25 16:02
I cannot reproduce this failure using nix v2.13.2 on macos 12.5.1 on an m1 macbook pro. Can you reliably reproduce this failure, and if so, what version of Nix and macos are you on?

```console
❯ nix run github:peterldowns/nix-search-cli -- --help
search for packages via search.nixos.org

Usage:
  nix-search ...query [flags]

Examples:
  # Search
  # ... like the web interface
  nix-search python linter
  nix-search --search "python linter"
  # ... by package name
  nix-search --name python
  nix-search --name 'emacsPackages.*'
  # ... by version
  nix-search --version 1.20
  nix-search --version '1.*'
  # ... by installed programs
  nix-search --program python
  nix-search --program "py*"
  # ... with ElasticSearch QueryString syntax
  nix-search --query-string="package_programs:(crystal OR irb)"
  nix-search --query-string='package_description:(MIT Scheme)'
  # ... on a specific channel
  nix-search --channel=unstable python3
  # ... or flakes
  nix-search --flakes wayland
  # ... with multiple filters and options
  nix-search --name go --version 1.20 --details

Flags:
  -c, --channel string        which channel to search in (default "unstable")
  -d, --details               show expanded details for each result
  -f, --flakes                search flakes instead of nixpkgs
  -h, --help                  help for nix-search
  -j, --json                  emit results in json-line format
  -m, --max-results int       maximum number of results to return (default 20)
  -n, --name string           search by package name
  -p, --program string        search by installed programs
  -q, --query-string string   search by elasticsearch querystring
  -s, --search string         default search, same as the website
  -v, --version string        search by version

~ on ☁️
❯ nix --version
nix (Nix) 2.13.2

~ on ☁️
❯ uname -a
Darwin pld-mbp-22 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
```

**Comment by ostrolucky** [comment] 2023-03-25 16:48
Yes for me this always happens so it's always reproducible for me

MacOS 13.2.1 (22D68)
nix (Nix) 2.13.2

**Comment by peterldowns** [comment] 2023-03-25 18:52
Thank you. Unfortunately, I don't know what's causing this problem for you and I am unable to reproduce it, so I'm going to close this issue. If you are able to come up with a fix, I would happily accept a PR. Depending on if you investigate further and what you find out, you may consider opening an issue against [the gomod2nix repo](https://github.com/nix-community/gomod2nix) since this looks like an issue building a golang dependency using their code.

**Closed as not planned by peterldowns** 2023-03-25 18:52 UTC
