### ISSUE TITLE
error: API failure[index_not_found_exception](index_or_alias=latest-37-nixos-unstable): no such index [latest-37-nixos-unstable]

### ISSUE THREAD

**Issue by ostrolucky** [peterldowns/nix-search-cli#8] opened 2023-03-24 08:51 UTC
```
❯ nix-search locust

 error: API failure[index_not_found_exception](index_or_alias=latest-37-nixos-unstable): no such index [latest-37-nixos-unstable]
```

**Comment by peterldowns** [comment] 2023-03-25 16:03
Duplicate of https://github.com/peterldowns/nix-search-cli/issues/6

**Closed as not planned by peterldowns** 2023-03-25 16:03 UTC
